version: '3'

services:
  cnn_model:
    image: osmolr/model-cnn-app:kerasCNN-flask
    container_name: cnn_model
    restart: on-failure
    networks:
      - backend

  labelling:
    build: ./labelling/
    container_name: labelling
    restart: on-failure
    volumes:
      - ./labelling/uploads/cnn:/usr/src/API/uploads/cnn
      - ./labelling/uploads/svm:/usr/src/API/uploads/svm
    networks:
      - backend

  data_preparation:
    build: ./data_preparation/
    container_name: data_preparation
    restart: on-failure
    networks:
      - backend

  authentication:
    # replace username/repo:tag with your name and image details
    container_name: authentication
    build: ./jwt/
    volumes:
      - .:/db
    restart: on-failure
    networks:
      - backend

  web-server:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      # if need to add https using certbot
      # - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - backend
    depends_on:
      - labelling
      - authentication
      - data_preparation

networks:
  backend:

volumes:
  db:

