version: "3"
services:
  labelling:
    build: ./labelling/
    ports:
      - "4000:4000"

  authentication:
    # replace username/repo:tag with your name and image details
    image: mecherefadelyoucef/jwt_microservice:latest
    build: ./jwt/
    volumes:
      - .:/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    
volumes:
  db:

